apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter
  namespace: monitoring
  labels:
    app: rabbitmq-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
    spec:
      containers:
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter:latest
        ports:
        - containerPort: 9419  # Exporter metric port
        env:
        - name: RABBIT_URL
          value: "http://rabbitmq:15672"   # RabbitMQ management API URL
        - name: RABBIT_USER
          value: "guest"                   # RabbitMQ username
        - name: RABBIT_PASSWORD
          value: "guest"                   # RabbitMQ password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter
  namespace: monitoring
spec:
  selector:
    app: rabbitmq-exporter
  ports:
  - protocol: TCP
    port: 9419
    targetPort: 9419