apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ecom-secret-provider
  namespace: dev
spec:
  provider: azure
  parameters:
    keyvaultName: aks-k8s-keyvault
    clientID: "clientID"
    objects: |
      array:
        - |
          objectName: "NEXTAUTH_SECRET"
          objectType: "secret"
          objectVersion: ""
    tenantID: "<Tenant ID>"  
  secretObjects:
    - secretName: imagepullsecret-billingapp
      type: kubernetes.io/dockerconfigjson
      data:
        - key: ".dockerconfigjson"
          objectName: "image-pull-secret-ecom"