apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret-provider
  namespace: dev
spec:
  provider: azure
  parameters:
    keyvaultName: aks-k8s-keyvault
    clientID: "<ClientID>"
    objects: |
      array:
        - |
          objectName: "MONGO-PASSWORD"
          objectType: "secret"
          objectVersion: ""
        - |
          objectName: "MONGO-USER"
          objectType: "secret"
          objectVersion: ""
    tenantID: "TenantID"
  secretObjects:
    - secretName: db-secret
      type: Opaque
      data:
        - key: MONGO_USER
          objectName: MONGO-USER
        - key: MONGO_PASSWORD
          objectName: MONGO-PASSWORD