# Use official Node.js image
FROM node:18-alpine AS builder
# Set working directory inside the container
WORKDIR /app
# Copy package.json and package-lock.json first (for better caching)
COPY package.json package-lock.json ./
# RUN apk add --no-cache openssl
# Install dependencies
RUN npm install
# Copy the rest of the application code
COPY . .
RUN npx prisma generate && npm run build

#stage : 2 Use built files
FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache openssl
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY . ./dist
RUN npx prisma generate && npm run build
# Expose port 3000 (adjust based on your app)
EXPOSE 3000

# Set environment variables (example)
ENV NODE_ENV=production

# Start the Node.js application
CMD ["node", "dist/app.js"]