apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  labels:
    app: rabbitmq
type: Opaque
# Using stringData lets you provide raw values. Kubernetes will encode them for you.
stringData:
  username: "guest"  # Replace with your desired username.
  password: "guest"