apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1  
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs
        image: anujtoppo/nextjs-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: NEXTAUTH_SECRET
        command: ["sh","-c","source .env && PORT=$PORT npm run start"]
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: nextjs-config-volume
          mountPath: /app/.env
          subPath: .env
        # - name: secret-store-inline
        #   mountPath: /mnt/secret-store-inline
      volumes:
      - name: nextjs-config-volume
        configMap:
          name: frontend-cm
      # - name: secret-store-inline
      #   csi:
      #     driver: secrets-store.csi.k8s.io
      #     readOnly: true
      #     volumeAttributes:
      #       secretProviderClass: ecom-secret-provider
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
  labels:
    app.kubernetes.io/part-of: nextjs-app
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3001  # External port
      targetPort: 3001  # Container port
  type: ClusterIP  # Internal communication only
