apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
        server {
            listen 8080;
            server_name dev.svc.cluster.local;

            # Proxy Next.js frontend requests
            location / {
                proxy_pass http://frontend-app.dev.svc.cluster.local:3001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            # Serve Next.js static files efficiently
            # location /_next/static {
            #     root /usr/share/nginx/html; # Ensure this matches the actual Next.js build path
            #     expires 30d;
            #     access_log off;
            # }

            # # Proxy backend API requests
            # location /api/ {
            #     proxy_pass http://backend-api.dev.svc.cluster.local:3000;
            #     proxy_set_header Host $host;
            #     proxy_set_header X-Real-IP $remote_addr;
            # }
        }
